#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Chemistry-PointGroup-Ci
version:      0.01
version_from: Ci.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
